site_name: My Docs
theme:
  name: material
  custom_dir: theme/
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    scheme: slate

extra_css:
  - css/styles.css

extra_javascript:
  - js/script.js

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://fortisureit.com"  target="_blank" rel="noopener">FortisureIT</a>

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true